# Generated by Django 5.2.3 on 2025-06-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='backups/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
