# Generated by Django 5.2.3 on 2025-06-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_bank', models.FileField(upload_to='upload/origem/')),
                ('destination_bank', models.FileField(upload_to='upload/destino/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('final_destination_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
